---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
implicit:
  - Поиск и фильтрация товаров может осуществляться как по одному критерию, так и по нескольким сразу
  - Перемещение по сайту должно происходить без перезагрузки страницы
  - Пользователь должен иметь фозможность оформить заказ
  - На сайте присутствует навигационная панель с постоянным доступом к каталогу толваров, корзине и выбору языка
  - При долгом соединении, сайт показывает, что происходит процесс загрузки
  - При просмотре корзины, показывает наименования товаров, количество, цену
  - Сайт должен корректно отображаться при разном разрешении экрана
  - При отсутствии товаров по запросу поиск должен возвращать сообщение "Nothing found!"
  - Все цены и валюты должны отображаться в соответствии с выбранным языком
