---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
  - На странице товара и в каталоге выводится название, рейтинг, цена товара со скидкой и без
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Корзина будет хранится в сессии браузера
implicit:
  - Поиск и фильтрация товаров может осуществляться как по одному критерию, так и по нескольким сразу
  - Перемещение по сайту должно происходить без перезагрузки страницы
  - На сайте присутствует навигационная панель с постоянным доступом к каталогу толваров, корзине и выбору языка
  - При долгом соединении, сайт показывает, что происходит процесс загрузки
  - При просмотре корзины, показывает наименования товаров, количество, цену
  - Сайт должен корректно отображаться при разном разрешении экрана
  - При отсутствии товаров по запросу поиск должен возвращать сообщение "Nothing found!"
  - При добавлении товаров в корзину, пользователь должен получать сообщение "Товар успешно добавлен в корзину!"
  - При успешном заказе товаров, заказу должен присваиваться индивидуальный номер отслеживания заказа
  - Магазин должен иметь возможность связаться с пользователем для уточнения деталей заказа
